name: Deploy Hospital Management Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t hospital-management:latest .

      - name: Save Docker Image
        run: docker save hospital-management:latest -o hospital-management.tar

      - name: Copy Docker Image to Remote VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hospital-management.tar"
          target: "/home/ubuntu/hospital-management.tar"

      - name: Deploy on Remote VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i hospital-management.tar
            docker stop hospital-app || true
            docker rm hospital-app || true
            docker run -d -p 8086:80 --name hospital-app hospital-management:latest
